"""Инициализация Бд

Revision ID: aee3144c15c3
Revises: 
Create Date: 2026-06-05 12:24:46.496513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee3144c15c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='auditlevel', native_enum=False), nullable=False, comment='Уровень лога: INFO, WARNING, ERROR.'),
    sa.Column('event_type', sa.Enum('PAYMENT_CREATED', 'PAYMENT_FAILED', 'PAYMENT_CANCELLED', 'PAYMENT_COMPLETED', 'PAYMENT_NOT_FOUND', 'PAYMENT_UI_NOT_FOUND', 'PAYMENT_NOT_OWNED_BY_USER', 'EMPTY_PAYMENT_LINK', 'ACCESS_GRANTED', 'ACCESS_REVOKED', 'VPN_KEY_CREATED', 'VPN_KEY_UPDATED', 'VPN_KEY_FETCHED', 'VPN_KEY_DELETED', 'TRIAL_ALREADY_GRANTED', 'TRIAL_GRANTED', 'NO_AVAILABLE_SERVERS', 'SERVER_NOT_FOUND', 'IS_PROCESSING', 'USER_NOT_FOUND', 'MESSAGE_NOT_FOUND', 'TICKET_NOT_FOUND', 'SUB_NOT_FOUND_IN_DB', 'KEY_CANCELLED', 'KEY_NOT_FOUND_IN_DB', 'KEY_NOT_FOUND_IN_VPN', 'KEY_NOT_OWNED_BY_USER', 'KEY_LIMIT', 'PLAN_NOT_FOUND', 'PAYING_OTHER', 'ADMIN_ACTION', 'DB_ERROR', 'VPN_ERROR', 'PAYMENT_PROVIDER_ERROR', 'UNEXPECTED_ERROR', 'SYSTEM_ERROR', name='auditeventtype', native_enum=False), nullable=False, comment='Тип бизнес-события (PAYMENT_COMPLETED, ACCESS_GRANTED и т.д.).'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='Основное сообщение лога.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания лога.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название тарифа.'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Длительность тарифа в секундах.'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Итоговая цена в рублях.'),
    sa.Column('base_price', sa.Integer(), nullable=True, comment='Цена без скидки в рублях.'),
    sa.Column('plan_type', sa.Enum('PAID', 'TRIAL', 'VIP', name='plantype', native_enum=False), nullable=False, comment='Тип тарифа: PAID, TRIAL, VIP.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Активен ли тариф.'),
    sa.CheckConstraint('base_price IS NULL OR base_price >= price', name='ck_plan_base_price_valid'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_plan_duration_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_plan_price_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_plans_plan_type'), 'plans', ['plan_type'], unique=False)
    op.create_index('uq_plan_trial_once', 'plans', ['plan_type'], unique=True, postgresql_where=sa.text("plan_type = 'TRIAL'"))
    op.create_index('uq_plan_vip_once', 'plans', ['plan_type'], unique=True, postgresql_where=sa.text("plan_type = 'VIP'"))
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, comment='Название сервера.'),
    sa.Column('panel_url', sa.String(length=255), nullable=False, comment='Ссылка на панель сервера.'),
    sa.Column('panel_username', sa.String(length=255), nullable=False, comment='Логин от панели сервера.'),
    sa.Column('panel_password', sa.String(length=255), nullable=False, comment='Пароль от панели сервера.'),
    sa.Column('host', sa.String(length=100), nullable=False, comment='host панели сервера.'),
    sa.Column('inbound_id', sa.Integer(), nullable=False, comment='id inbound, в котором хранятся ключи.'),
    sa.Column('inbound_name', sa.String(length=50), nullable=True, comment='Название inbound, в котором хранятся ключи. Не является источником истины.'),
    sa.Column('default_key_name', sa.String(length=50), nullable=True, comment='Название ключа по умолчанию.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Активен ли сервер.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания сервера в базе данных.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_servers_created_at'), 'servers', ['created_at'], unique=False)
    op.create_index(op.f('ix_servers_is_active'), 'servers', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор пользователя (PK).'),
    sa.Column('tg_id', sa.BigInteger(), nullable=False, comment='Telegram ID пользователя (уникальный).'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Username пользователя в Telegram (может отсутствовать).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время (UTC) регистрации пользователя.'),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг блокировки пользователя.'),
    sa.Column('agreed_to_policy', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Согласен ли пользователь на обработку персональных данных и оферту.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя, у которого есть эта подписка.'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='id тарифа, на который подписался пользователь.'),
    sa.Column('sub_token', sa.String(length=32), nullable=False, comment='Уникальный токен для subscription URL.'),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата получение подписки пользователем.'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='Дата окончания подписки пользователя.'),
    sa.CheckConstraint('end_at >= start_at', name='ck_subscriptions_end_after_start'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_end_at'), 'subscriptions', ['end_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_sub_token'), 'subscriptions', ['sub_token'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор обращения в поддержку (PK).'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя, который отправил это обращение.'),
    sa.Column('thread_id', sa.Integer(), nullable=False, comment='id топика в группе админов.'),
    sa.Column('title', sa.Text(), nullable=False, comment='Первые символы первого сообщения. Используется как превью в списке обращений.'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='ticketstatus', native_enum=False), nullable=False, comment='Статус обращения: открыт, закрыт'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания обращения.'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Время закрытия обращения.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_thread_id'), 'tickets', ['thread_id'], unique=True)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_index('uq_ticket_user_single_open', 'tickets', ['user_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_id', sa.Integer(), nullable=False, comment='id подписки, в которую входит ключ.'),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='id сервера, на котором расположен ключ.'),
    sa.Column('vless_link', sa.String(length=500), nullable=False, comment='vless ссылка ключа. Важен как кэш, чтобы уменьшить количество запросов к xui.'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_keys_server_id'), 'access_keys', ['server_id'], unique=False)
    op.create_index(op.f('ix_access_keys_sub_id'), 'access_keys', ['sub_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор сообщения в поддержку (PK).'),
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='id обращения в поддержку.'),
    sa.Column('sender_type', sa.Enum('SUPPORT', 'USER', name='messagesendertype', native_enum=False), nullable=False, comment='Отправитель сообщения: SUPPORT, USER.'),
    sa.Column('text', sa.Text(), nullable=False, comment='Сообщение отправителя.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания сообщения.'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_ticket_created', 'messages', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_ticket_id'), 'messages', ['ticket_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь, совершивший платеж.'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='Тариф, за который был произведён платеж.'),
    sa.Column('sub_id', sa.Integer(), nullable=True, comment='Связь с подпиской, который был выдан по этому платежу.'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Сумма платежа.'),
    sa.Column('payment_method', sa.Integer(), nullable=True, comment='Способ оплаты (enum PaymentMethod)'),
    sa.Column('type', sa.Enum('PURCHASE', 'TRIAL', name='paymenttype', native_enum=False), nullable=False, comment='Тип платежа (покупка, пробный период).'),
    sa.Column('action', sa.Enum('CREATE', 'RENEW', name='paymentaction', native_enum=False), nullable=False, comment='Тип действия над ключом: создание, продление.'),
    sa.Column('provider', sa.Enum('PLATEGA', 'INTERNAL', name='paymentprovider', native_enum=False), nullable=False, comment='Платёжный провайдер (например, YooMoney, Qiwi, Telegram).'),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False, comment='ID платежа у провайдера.'),
    sa.Column('payment_url', sa.Text(), nullable=True, comment='Ссылка для оплаты'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'PROCESSING', name='paymentstatus', native_enum=False), nullable=False, comment='Статус платежа: pending, completed, failed, canceled.'),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True, comment='Время выдачи доступа пользователю. Null, если доступ ещё не выдан.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания записи платежа.'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='Время подтверждённого платежа.'),
    sa.CheckConstraint('price >= 0', name='ck_payments_price_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_provider_payment_id')
    )
    op.create_index(op.f('ix_payments_action'), 'payments', ['action'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_sub_id'), 'payments', ['sub_id'], unique=False)
    op.create_index(op.f('ix_payments_type'), 'payments', ['type'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index('uq_user_pending_once', 'payments', ['user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('uq_user_trial_once', 'payments', ['user_id'], unique=True, postgresql_where=sa.text("type = 'TRIAL'"))
    op.create_table('payment_ui_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='Ссылка на платеж, для которого сохраняется Telegram UI-сообщение.'),
    sa.Column('tg_user_id', sa.Integer(), nullable=False, comment='Telegram id пользователя.'),
    sa.Column('tg_chat_id', sa.Integer(), nullable=False, comment='ID чата пользователя в Telegram, где было отправлено сообщение с оплатой.'),
    sa.Column('tg_message_id', sa.Integer(), nullable=False, comment='ID сообщения в Telegram, которое должно быть обновлено после изменения статуса платежа.'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_ui_state_payment_id'), 'payment_ui_state', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_ui_state_payment_id'), table_name='payment_ui_state')
    op.drop_table('payment_ui_state')
    op.drop_index('uq_user_trial_once', table_name='payments', postgresql_where=sa.text("type = 'TRIAL'"))
    op.drop_index('uq_user_pending_once', table_name='payments', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_sub_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_action'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messages_ticket_id'), table_name='messages')
    op.drop_index('ix_messages_ticket_created', table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_access_keys_sub_id'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_server_id'), table_name='access_keys')
    op.drop_table('access_keys')
    op.drop_index('uq_ticket_user_single_open', table_name='tickets', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_thread_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_sub_token'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_end_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_servers_is_active'), table_name='servers')
    op.drop_index(op.f('ix_servers_created_at'), table_name='servers')
    op.drop_table('servers')
    op.drop_index('uq_plan_vip_once', table_name='plans', postgresql_where=sa.text("plan_type = 'VIP'"))
    op.drop_index('uq_plan_trial_once', table_name='plans', postgresql_where=sa.text("plan_type = 'TRIAL'"))
    op.drop_index(op.f('ix_plans_plan_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
