"""Инициализация БД

Revision ID: d051530c7379
Revises: 
Create Date: 2026-03-07 16:55:26.275859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd051530c7379'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='auditlevel', native_enum=False), nullable=False, comment='Уровень лога: INFO, WARNING, ERROR'),
    sa.Column('event_type', sa.Enum('PAYMENT_FAILED', 'PAYMENT_CANCELLED', 'PAYMENT_NOT_FOUND', 'ACCESS_GRANTED', 'ACCESS_REVOKED', 'XUI_ADD', 'XUI_UPDATE', 'XUI_GET', 'XUI_DELETE', 'KEY_CANCELLED', 'KEY_NOT_FOUND_IN_DB', 'KEY_NOT_FOUND_IN_VPN', 'KEY_NOT_OWNED_BY_USER', 'KEY_LIMIT', 'VPN_ERROR', 'PAYING_OTHER', 'ADMIN_ACTION', 'SYSTEM_ERROR', name='auditeventtype', native_enum=False), nullable=False, comment='Тип бизнес-события (PAYMENT_COMPLETED, ACCESS_GRANTED и т.д.)'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='Основное сообщение лога'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Дополнительный контекст (user_id, payment_id, данные XUI и т.д.)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания лога'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название тарифа'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Длительность тарифа в секундах'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Итоговая цена в рублях'),
    sa.Column('base_price', sa.Integer(), nullable=True, comment='Цена без скидки в рублях'),
    sa.Column('plan_type', sa.Enum('PAID', 'TRIAL', 'VIP', name='plantype', native_enum=False), nullable=False, comment='Тип тарифа: PAID, TRIAL, VIP'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Активен ли тариф'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_plans_plan_type'), 'plans', ['plan_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор пользователя (PK).'),
    sa.Column('tg_id', sa.BigInteger(), nullable=False, comment='Telegram ID пользователя (уникальный).'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Username пользователя в Telegram (может отсутствовать).'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время (UTC) регистрации пользователя.'),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг блокировки пользователя.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя, у которого есть эта подписка.'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='id тарифа, на который подписался пользователь.'),
    sa.Column('start_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата получение подписки пользователем.'),
    sa.Column('end_at', sa.DateTime(), nullable=False, comment='Дата окончания подписки пользователя.'),
    sa.Column('price_at_purchase', sa.Integer(), nullable=False, comment='Сумма, за которую приобрели подписку.'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_keys_end_at'), 'access_keys', ['end_at'], unique=False)
    op.create_index(op.f('ix_access_keys_plan_id'), 'access_keys', ['plan_id'], unique=False)
    op.create_index(op.f('ix_access_keys_user_id'), 'access_keys', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь, совершивший платеж'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='Тариф, за который был произведён платеж'),
    sa.Column('key_id', sa.Integer(), nullable=True, comment='Связь с подпиской/ключом, который был выдан по этому платежу'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Сумма платежа'),
    sa.Column('type', sa.Enum('PURCHASE', 'TRIAL', name='paymenttype', native_enum=False), nullable=False, comment='Тип платежа (покупка, пробный период)'),
    sa.Column('action', sa.Enum('CREATE', 'RENEW', name='paymentaction', native_enum=False), nullable=False, comment='Тип действия над ключом: создание, продление'),
    sa.Column('provider', sa.Enum('YOUMONEY', 'INTERNAL', name='paymentprovider', native_enum=False), nullable=False, comment='Платёжный провайдер (например, YooMoney, Qiwi, Telegram)'),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False, comment='ID платежа у провайдера'),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus', native_enum=False), nullable=False, comment='Статус платежа: pending, completed, failed'),
    sa.Column('granted_at', sa.DateTime(), nullable=True, comment='Время выдачи доступа пользователю. Null, если доступ ещё не выдан'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания записи платежа'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='Время подтверждённого платежа'),
    sa.ForeignKeyConstraint(['key_id'], ['access_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_provider_payment_id')
    )
    op.create_index(op.f('ix_payments_action'), 'payments', ['action'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_key_id'), 'payments', ['key_id'], unique=False)
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_type'), 'payments', ['type'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index('uq_user_trial_once', 'payments', ['user_id'], unique=True, postgresql_where=sa.text("type = 'TRIAL'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_trial_once', table_name='payments', postgresql_where=sa.text("type = 'TRIAL'"))
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_key_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_action'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_access_keys_user_id'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_plan_id'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_end_at'), table_name='access_keys')
    op.drop_table('access_keys')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_plan_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
